// Auth
export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const START_REGISTER = 'START_REGISTER';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';

export const SUCCESS_GOOGLE_LOGIN = 'SUCCESS_GOOGLE_LOGIN';
export const ERROR_GOOGLE_LOGIN = 'ERROR_GOOGLE_LOGIN';

export const RESPONSE_FACEBOOK_LOGIN = 'RESPONSE_FACEBOOK_LOGIN';

export const LOGOUT = 'LOGOUT';

// Death Predictions
export const START_GET_DEATH_PREDICTIONS = 'START_GET_DEATH_PREDICTIONS';
export const SUCCESS_GET_DEATH_PREDICTIONS = 'SUCCESS_GET_DEATH_PREDICTIONS';
export const ERROR_GET_DEATH_PREDICTIONS = 'ERROR_GET_DEATH_PREDICTIONS';

// Countries
export const START_GET_COUNTRIES = 'START_GET_COUNTRIES';
export const SUCCESS_GET_COUNTRIES = 'SUCCESS_GET_COUNTRIES';
export const ERROR_GET_COUNTRIES = 'ERROR_GET_COUNTRIES';