// Auth
export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const SUCCESS_GOOGLE_LOGIN = 'SUCCESS_GOOGLE_LOGIN';
export const ERROR_GOOGLE_LOGIN = 'ERROR_GOOGLE_LOGIN';

export const RESPONSE_FACEBOOK_LOGIN = 'RESPONSE_FACEBOOK_LOGIN';